### ISSUE TITLE
Case insensitivity of route handlers

### ISSUE THREAD

**Issue by jguo35** [scssyworks/silkrouter#32]
Would it be possible to specify that we want route handlers to be triggered without caring about the case sensitivity of the url?

For example, if we have `route("#/my/route", function () { ... })`, I would want it to be triggered by navigating to "#/mY/ROUte" as well as "#/my/route".

To extend to this, it would be great if you could supply a function when defining routes that determines whether or not a particular url will trigger that route. For example:
```js
route(
  function(route) {
    return route.toLowerCase() === "#/my/route"; // return true to trigger the route handler
  },
  function(config) { ... }
);
```

**Comment by scssyworks** [comment]
Hi @jguo35 
That's a good suggestion! I will incorporate it in the next version.
Meanwhile you can use generic route if that solves your problem:
```js
route(({ route }) => {
  ...
});
```

**Comment by scssyworks** [comment]
Hi @jguo35 
Please use ``routeIgnoreCase`` method to set case insensitive routes. Please refer to README for more details. Let me know if you face any issues.
