### ISSUE TITLE
How to set a default case for 404.

### ISSUE THREAD

**Issue by JesusADS** [scssyworks/silkrouter#55]
Hi, is there a way to catch undefined routes? (I'm using jquery version)

I have for example the routes `/a` and `/b`. I would like to be able to handle anything diferent from those 2 routes to go to a 404 page. Something like:

```
$.route('?', (e) => {
    // show 404 page
});
```

is it possible?
Thanks!

**Comment by JesusADS** [comment]
UPDATE: I try to change my code to `silkrouter` to use this aproach:

```
route((e) => {
    switch(e.route) {
        case '/route1': ...;
        case '/route2': ...;
        default: ...; // Handle 404
    }
});
```

the default does what I needed, but now my routes with path params stop working, because the `e.route` is the route with the paths translated, not the `/route/:paramX/:paramY`.

Any idea on how to keep routes with path params and the default route for undefined ones?

Thanks

**Comment by scssyworks** [comment]
Hi @JesusADS 
Silkrouter ships ``routeParams`` function which can be used to extract route params as in your case.

```js
import { routeParams } from 'silkrouter';

route(e => {
  const keyValueMap = routeParams('/route/:paramX/:paramY', e.route);
  ...
});
```

The function returns a key value map for all the matched route parameters. Hope this helps!

**Comment by scssyworks** [comment]
I am closing this issue. Feel free to open another issue if you need more help. Thanks for your contribution! :)

**Comment by JesusADS** [comment]
Hi @scssyworks thanks for your answer, I think you didn't understand my problem.

"routeParams" indeed get me the route params, but that doesn't help me to go to that route. Let me give you an example:

```
const { router, route, routeParams } = silkrouter;
        
route((e) => {
    switch(e.route) {
        case '/':
            // HOME
            break;
        case '/tasks':
            // Show all tasks
            break;
        case '/tasks/:id':
            // Show task with ID :id
            break;
        case '/tasks/:id/users':
            // Show users from task with ID :id
            break;
        case '/tasks/:id/users/:userId':
            // Show user with ID :userId from task with ID :id
            break;
        default:
            // Unknown url, show 404
            break;
    }
});
```

In this example there are 5 routes, and a default 404, but with this approach, only 3 work (the ones without params), the others never match and go to the default 404.

I could add the `routeParams`, but I would have to do it for each route with params (that could be 500 routes), that isn't very practical, and even if I do, there are routes with the same params that I would not know which one is, for example:

``` 
const keyValueMap = routeParams('/tasks/:id', e.route);
```
for the route `/tasks/50` would return `{id: 50}`, and

``` 
const keyValueMap = routeParams('/tasks/:id/users', e.route);
```
for the route `/tasks/50/users` would also return `{id: 50}`.


How do I know in which route I am, to be able to do something with it?

I maintain my first suggeston that the best way to resolve this is with something like:

```
route('?', (e) => {
    // Unknown url, show 404 
});
```

Regards

**Comment by scssyworks** [comment]
Hi @JesusADS ,
I understand your problem now. You can still use regular routing. The only thing that's missing is how do we handle a route that does not have a match. Here's a not so very intuitive solution but I think it should work:

```js
import { route, routeParams } from 'silkrouter';
...
route('/', () => { ... });
route('/tasks', () => { ... });
route('/tasks/:id', () => { ... });
route('/tasks/:id/users', () => { ... });
route('/tasks/:id/users/:userId', () => { ... });
// Default
route(e => {
  const activeRoutes = ['/', '/tasks'];
  if (Object.keys(routeParams('/tasks/:id', e.route)).length) activeRoutes.push(e.route);
  if (Object.keys(routeParams('/tasks/:id/users', e.route)).length) activeRoutes.push(e.route);
  if (Object.keys(routeParams('/tasks/:id/users/:userId', e.route)).length) activeRoutes.push(e.route);
  if (!activeRoutes.includes(e.route)) {
     // Handle 404 scenario
  }
});
```

Meanwhile I am keeping this ticket open while I analyze your suggestion. If you have a ready solution already then feel free to raise a PR.

Let me know if you still have any questions.

**Comment by JesusADS** [comment]
Thanks again for your answer @scssyworks, 

> 
> Hi @JesusADS ,
> I understand your problem now. You can still use regular routing. The only thing that's missing is how do we handle a route that does not have a match. 


That is exactly the need I have, and the request in my first comment.


> 
> Here's a not so very intuitive solution but I think it should work:
> 
> ```js
> import { route, routeParams } from 'silkrouter';
> ...
> route('/', () => { ... });
> route('/tasks', () => { ... });
> route('/tasks/:id', () => { ... });
> route('/tasks/:id/users', () => { ... });
> route('/tasks/:id/users/:userId', () => { ... });
> // Default
> route(e => {
>   const activeRoutes = ['/', '/tasks'];
>   if (Object.keys(routeParams('/tasks/:id', e.route)).length) activeRoutes.push(e.route);
>   if (Object.keys(routeParams('/tasks/:id/users', e.route)).length) activeRoutes.push(e.route);
>   if (Object.keys(routeParams('/tasks/:id/users/:userId', e.route)).length) activeRoutes.push(e.route);
>   if (!activeRoutes.includes(e.route)) {
>      // Handle 404 scenario
>   }
> });
> ```
> 


I see your point, is crearly unmanageable for more that 5-10 routes, but it certainly does the trick.


> 
> Meanwhile I am keeping this ticket open while I analyze your suggestion. If you have a ready solution already then feel free to raise a PR.
> 
> Let me know if you still have any questions.
> 


I haven't had time to see your code, but if I do and see a clear solution, I will surely let you know.

Thanks!

**Comment by scssyworks** [comment]
Hi @JesusADS,

I have added couple of methods that should simplify our solution:

```js
import { route, routeParams } from 'silkrouter';
...
route('/', () => { ... });
route('/tasks', () => { ... });
route('/tasks/:id', () => { ... });
route('/tasks/:id/users', () => { ... });
route('/tasks/:id/users/:userId', () => { ... });
// Default
route(e => {
  if (!router.includes(router.list().filter(route => route !== '*'), e.route)) {
     // Handle 404 scenario
  }
});
```

Your suggestion of using "?" for error route is good (theoretically). Unfortunately impossible to implement. The reason is "generic" routing which listens to each and every route change, and will also listen to error routes. Which means practically we cannot reach "?" route if we are using generic routing.

```js
route(e => { ... }); // This listens to everything
route('?', () => { ... }); // This will never be reached
```

Instead, I have simplified the way we can compare current path name with existing routes.

Let me know if this solution works for you. Feel free to open another defect if you face any other issue.

**Comment by scssyworks** [comment]
Please upgrade to version 3.5.0

**Comment by JesusADS** [comment]
Hi @scssyworks 

It works great! Thanks for your help. I'll continue to test it and let you know if I find something else.

Thanks again 😄👍
