### ISSUE TITLE
Request for demo repo

### ISSUE THREAD

**Issue by tacman** [scssyworks/silkrouter#65]
Congrats on the (near) release of version 4!

Do you have a demo repo anywhere that uses either version?  I'd love to see the proper way to use silkrouter, especially within a class/module.  My current code is a bunch of onClick handlers which I'm slowly converting to silkrouter, but it doesn't feel very clean, I'm sure there's a better way.

Thanks.

**Comment by scssyworks** [comment]
Hi @tacman ,
Thanks your posting your query. For silkrouter version 3 you can refer to following demo link:
https://silkrouter.herokuapp.com/

For version 4 I am building an interactive demo. It's a work in progress. I will update the documentation once it's ready.

Let me know if you have any further questions.

Best,
Sachin

**Comment by tacman** [comment]
Awesome, thanks!  Is the source code available on github?

**Comment by scssyworks** [comment]
Yes! The current master branch has latest code for version 4. For version 3 please checkout following branch:
https://github.com/scssyworks/silkrouter/tree/feature/ver3

**Comment by tacman** [comment]
Sorry, I'm still not seeing it.  I'd like to clone the demo app (hosted on
heroku), not this github repository with the source code.

**Comment by scssyworks** [comment]
Hi @tacman,
Please refer to this project:
https://github.com/scssyworks/jqueryrouter-example
